import React, { useState } from 'react';

const QuickBot = () => {
    const [market,setMarket]=useState('1HZ15V'); const [strategy,setStrategy]=useState('Even / Odd'); const [stake,setStake]=useState('0.50'); const [martingale,setMartingale]=useState('2'); const [wins,setWins]=useState('4'); const [stopLoss,setStopLoss]=useState('50'); const [running,setRunning]=useState(false); const [message,setMessage]=useState('');
    const start=()=>{setRunning(true);setMessage('Demo bot started. No live order was sent to Deriv.');};
    return <main style={{minHeight:'100%',background:'radial-gradient(circle at 50% 0,#152c62,#030b20 60%)',color:'#fff',padding:'25px 14px 100px'}}><div style={{maxWidth:1000,margin:'0 auto'}}>
        <header><small style={{color:'#26ddec',fontWeight:900,letterSpacing:2}}>QUICK BOT</small><h1 style={{fontSize:40,margin:'8px 0'}}>Build and run a quick bot</h1><p style={{opacity:.7}}>Create a compact digit strategy, review the parameters, then start it in demo mode.</p></header>
        <section style={{marginTop:18,padding:20,border:'1px solid #17638b',borderRadius:18,background:'rgba(3,18,42,.94)'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
            <label>Market<select value={market} onChange={e=>setMarket(e.target.value)} style={input}>{[['1HZ10V','Volatility 10 (1s)'],['1HZ15V','Volatility 15 (1s)'],['1HZ25V','Volatility 25 (1s)'],['1HZ50V','Volatility 50 (1s)'],['1HZ100V','Volatility 100 (1s)']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>
            <label>Strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)} style={input}><option>Even / Odd</option><option>Over / Under</option><option>Matches / Differs</option></select></label>
            <label>Stake<input value={stake} onChange={e=>setStake(e.target.value)} type='number' min='.35' step='.01' style={input}/></label><label>Martingale<input value={martingale} onChange={e=>setMartingale(e.target.value)} type='number' min='1' step='.1' style={input}/></label>
            <label>Number of wins (stop after)<input value={wins} onChange={e=>setWins(e.target.value)} type='number' min='1' style={input}/></label><label>Stop loss<input value={stopLoss} onChange={e=>setStopLoss(e.target.value)} type='number' min='1' style={input}/></label>
        </div><div style={{marginTop:18,padding:18,border:'1px solid #1b5273',borderRadius:12,background:'#07172e'}}><h2 style={{marginTop:0}}>Bot rule</h2><p>On <b>{market}</b>, scan <b>{strategy}</b>. Stake <b>${stake}</b>, multiplier <b>{martingale}×</b>, stop after <b>{wins}</b> wins or <b>${stopLoss}</b> loss.</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:16}}><button onClick={start} style={{padding:'13px 22px',border:0,borderRadius:9,background:'#15b8e7',fontWeight:900}}>{running?'Bot running':'Start Demo Bot'}</button><button onClick={()=>{setRunning(false);setMessage('Demo bot stopped.');}} style={{padding:'13px 22px',border:'1px solid #3d607d',borderRadius:9,background:'#07172e',color:'#fff',fontWeight:900}}>Stop</button></div>{message&&<div style={{marginTop:12,color:'#46e5b0',fontWeight:800}}>{message}</div>}</section>
        <section style={{marginTop:16,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{[['01','Select market','Choose a live digit index.'],['02','Choose contract','Even/Odd, Over/Under or Matches/Differs.'],['03','Control risk','Stake, martingale and stop rules.']].map(([n,t,d])=><div key={n} style={{padding:18,border:'1px solid #174b75',borderRadius:14,background:'rgba(4,20,45,.8)'}}><b style={{color:'#24dced'}}>{n}</b><h3>{t}</h3><p style={{opacity:.65}}>{d}</p></div>)}</section>
    </div></main>;
};
const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',padding:11,marginTop:5,borderRadius:8,border:'1px solid #27708e',background:'#07152b',color:'#fff'};
export default QuickBot;
